### ISSUE TITLE
Fix cert issues

### ISSUE THREAD

**Issue by throwaway96** [throwaway96/webos-homebrew-channel#1]
Support adding CA certs on webOS <5.

**Comment by throwaway96** [comment]
Done. Could use some cleanup though.

**Comment by Presjar** [comment]
Have given this a test.. Now able to install apps with success but items that need root elevation don't seem to work for newly installed apps but continue to work fine for those that were granted the elevation previously.  I use PicCap and HyperHDR. These work fine. But when I install the DVD screensaver, Aerial Screensaver or the VNCServer(Fixed) they don't work.

Hyperion.NG shows service elevated as No.

Edit: I installed the rev2 test using the developer tool on Windows.

**Comment by setrin** [comment]
Same. Installed rev2, PicCap installed successfully, but couldn't elevate. After downgrading HC to 0.6.3 elevation was successful and PicCap ran as expected.

**Comment by throwaway96** [comment]
You haven't provided enough information to reproduce your problem. This isn't the appropriate place anyway.
